
/* #include "version.h" when build_info.xml generates it */

/* These are the values for Mac OS X */
#define DAEMON_NAME 			"tagEventord"
#define DEFAULT_LOCK_FILE_DIR	"/var/run/tagEventor"
#define DEFAULT_COMMAND_DIR		"/Library/Application Support/tagEventor"
#define VERSION_STRING			"0.1.0" /* combination of VERSION_CODE, BUILD_TIME, VERSION_NUMBER generated by build_info.xml" */
