# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=200)),
                ('activity_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ap', models.IntegerField(default=0)),
                ('protests', models.IntegerField(default=0)),
                ('thanks', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbeamd.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=4000)),
                ('comment_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
                ('username', models.CharField(max_length=200)),
                ('eta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('priority', models.IntegerField(blank=True, default=3)),
                ('ap', models.IntegerField(default=0)),
                ('repeat_after_days', models.IntegerField(default=-1)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cbeamd.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_open', models.BooleanField(default=False)),
                ('airlock_stripe_mode', models.IntegerField(default=1)),
                ('airlock_volume', models.IntegerField(default=42)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('logintime', models.DateTimeField()),
                ('extendtime', models.DateTimeField(auto_now_add=True)),
                ('logouttime', models.DateTimeField()),
                ('eta', models.CharField(blank=True, max_length=200)),
                ('etatimestamp', models.DateTimeField(auto_now_add=True)),
                ('etd', models.CharField(blank=True, max_length=200)),
                ('etdtimestamp', models.DateTimeField(auto_now_add=True)),
                ('nickspell', models.CharField(blank=True, max_length=200)),
                ('reminder', models.CharField(blank=True, max_length=200)),
                ('remindertimestamp', models.DateTimeField(auto_now_add=True)),
                ('lastlocation', models.CharField(blank=True, max_length=200)),
                ('etasub', models.BooleanField(default=False)),
                ('arrivesub', models.BooleanField(default=False)),
                ('autologout', models.IntegerField(default=600)),
                ('wlanlogin', models.BooleanField(default=False)),
                ('ap', models.IntegerField(default=0)),
                ('stats_enabled', models.BooleanField(default=False)),
                ('rfid', models.CharField(default=b'', max_length=200)),
                ('push_missions', models.BooleanField(default=True)),
                ('push_boarding', models.BooleanField(default=True)),
                ('push_eta', models.BooleanField(default=True)),
                ('stealthmode', models.DateTimeField(auto_now_add=True)),
                ('no_google', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usercount', models.IntegerField(default=0)),
                ('etacount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('regid', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cbeamd.User')),
            ],
        ),
        migrations.AddField(
            model_name='missionlog',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cbeamd.User'),
        ),
        migrations.AddField(
            model_name='mission',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, to='cbeamd.User'),
        ),
        migrations.AddField(
            model_name='activitylogcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbeamd.User'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='cbeamd.ActivityLogComment'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbeamd.Mission'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbeamd.User'),
        ),
    ]
