# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeamd', '0002_auto_20160113_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='priority',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
