# Generated by Django 2.1.2 on 2018-10-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbeamd', '0004_auto_20180213_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionlog',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cbeamd.Mission'),
        ),
    ]
