# Generated by Django 5.2.14 on 2026-05-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeamd', '0005_auto_20181005_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='user',
            name='rfid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='cbeamd_acti_timesta_a8a70d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='cbeamd_acti_user_id_68352e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity'], name='cbeamd_acti_activit_8878b8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='cbeamd_user_usernam_72724b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='cbeamd_user_status_637ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['logintime'], name='cbeamd_user_loginti_a8ae5a_idx'),
        ),
    ]
