#! /bin/bash

### BEGIN INIT INFO
# Provides:          c_out daemon
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start c_out daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

DAEMON=/home/smile/projects/c-beam/c_outd/c_outd.py

case "$1" in
  start)
    echo "Starting c_out daemon"

    # Run start-stop-daemon, the $DAEMON variable contains the path to the
    # application to run
    start-stop-daemon --start --pidfile $WSGI_PIDFILE \
        --user smile --group smile \
        --chuid smile \
        --exec "$DAEMON"
    ;;
  stop)
    echo "Stopping c_out daemon"

    # Start-stop daemon can also stop the application by sending sig 15
    # (configurable) to the process id contained in the run/pid file
    start-stop-daemon --stop --pidfile $WSGI_PIDFILE --verbose
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/c_out {start|stop}"
    exit 1
    ;;
esac

exit 0

