#!/bin/bash
# using the #! trick you can execute with whatever you like
# Example "generic" tag event script for tagEventor from autelic
# See http://www.autelic.org for more on autelic
# See http://code.google.com/p/tc-squared for more on tagEventor
# parameters passed are:
# $1 = UID (unique ID of the tag, as later we may use wildcard naming)
# $2 = Event Type (IN for new tag placed on reader, OUT for tag removed from reader)

# get the type of OS we are running on
OS=`uname`

# show a message in a dialog on the screen
if [[ $2 = "IN" ]]
then
    cp scripts/default scripts/$1 
fi
