#! /usr/bin/python

from ldapRfid import LdapRfidCheck
import sys, re
import login

import socket

MCAST_GRP = '10.0.1.255'
MCAST_PORT = 7343





logindelta = 10
timeoutdelta = 600

if (len(sys.argv) != 3):
    print("Usage %s <RFID_UUID>\n" % sys.argv[0])
    print("Search ldap for rfid-tag\n")
    sys.exit(1)

rfidUUid = sys.argv[1]

# send rfid via udp broadcast
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
#sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 2)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, True)
sock.sendto(rfidUUid, (MCAST_GRP, MCAST_PORT))

# debug output
print "ldap: %s" % rfidUUid

# anonymous bind against lea
f = LdapRfidCheck("ldap://10.0.1.7:389/", 'ou=crew,dc=c-base,dc=org', '', '', 'rfid', '(memberOf=cn=crew,ou=groups,dc=c-base,dc=org)')
userDn = f.getUserForRfid(rfidUUid)

if userDn == None:
    # unknown RFID tag
    login.unknowntag(rfidUUid)
    print "unknown tag"
    sys.exit(1)

m = re.search('uid=(.*),ou=crew,dc=c-base,dc=org', userDn)
if m == None:
    print "wrong dn format"
    sys.exit(1)

user = m.group(1)

result = login.login(user, timeoutdelta)
print "%s: %s" % (result, user)
