#! /usr/bin/python

from ldapRfid import LdapRfidCheck
import sys, re
import login

print "ldap"

logindelta = 10
timeoutdelta = 600

if (len(sys.argv) != 3):
    print("Usage %s <RFID_UUID>\n" % sys.argv[0])
    print("Search ldap for rfid-tag\n")
    sys.exit(1)

rfidUUid = sys.argv[1]
# anonymous bind against lea
f = LdapRfidCheck("ldap://10.0.1.7:389/", 'ou=crew,dc=c-base,dc=org', '', '', 'rfid', '(memberOf=cn=crew,ou=groups,dc=c-base,dc=org)')
userDn = f.getUserForRfid(rfidUUid)

if userDn == None:
    # unknown RFID tag
    print "unknown tag"
    sys.exit(1)

m = re.search('uid=(.*),ou=crew,dc=c-base,dc=org', userDn)
if m == None:
    print "wrong dn format"
    sys.exit(1)

user = m.group(1)

result = login.login(user, timeoutdelta)
print "%s: %s" % (result, user)
