#! /usr/bin/python

from ldapRfid import LdapRfidCheck
import sys

print sys.argv

if (len(sys.argv) != 3):
    print("Usage %s <RFID_UUID>\n" % sys.argv[0])
    print("Search ldap for rfid-tag\n")
    sys.exit(1)

rfidUUid = sys.argv[1]
# anonymous bind against lea
f = LdapRfidCheck("ldap://10.0.1.7:389/", 'ou=crew,dc=c-base,dc=org', '', '', 'rfid', '(memberOf=cn=crew,ou=groups,dc=c-base,dc=org)')
userDn = f.getUserForRfid(rfidUUid)
#print(userDn)

#result = login.login(user, timeoutdelta)
#if result == "login":
    #login.tts("julia", "hallo %s, willkommen an bord" % nickspell)
#elif result == "logout":
    #login.tts("julia", "guten heimflug %s" % nickspell)
#else:
    #print "ignore"
