#! /usr/bin/python

import login
import datetime
import os.path

user="test"
nickspell = "test"

logindelta = 10
timeoutdelta = 600


result = login.login(user, timeoutdelta)
if result == "login":
    print "%s logged in." % user
    #login.tts("julia", "hallo %s, willkommen an bord" % nickspell)
elif result == "logout":
    print "%s logged out." % user
    #login.tts("julia", "guten heimflug %s" % nickspell)
else:
    print "ignore"
